language: android
android:
  components:
    # use the latest revision of Android SDK Tools
     #- tools
     #- platform-tools

    # The BuildTools version used by our project
    - build-tools-19.1.0

    # The SDK version used to compile our project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # System images specified to run emulators during our tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-17
